I this course we will discuss Lists, Numpy Arrays (Numpy Dataframes), and Pandas Arrays (Pandas Dataframes. These are the main Data Storage and Manipulation tools in Python. Let's start with the simplest of three, Lists.





In [4]:
# Define a Scalar Variable
a = 4
print (a)

# Define a one-dimensional list; i.e. a vector
a = [2,3,4]
print (a)

# Define a two-dimensional list; i.e. a matrix
# following is a 3 by 2 matrix; i.e. 3 rows and 2 columns
a = [[1,2], [-9, 5], [3,3]]
print (a)

4
[2, 3, 4]
[[1, 2], [-9, 5], [3, 3]]


Lists have limited functionality. Numpy Array is like a more advanced List.

In [5]:
# import numpy library
import numpy as np

In [7]:
# Define a 1-dimensional Numpy array
a = np.array([2,3,4])
print (a)

# Define a 2-dimensional Numpy array
a = np.array([[1,2], [-9, 5], [3,3]])
print (a)

# notice how numpy, prints a matrix in a better way

[2 3 4]
[[ 1  2]
 [-9  5]
 [ 3  3]]


**To work with data, you should be able to quickly choose any element of a vector or matrix**

In [13]:
# choosing different elements of a Numpy array (dataframe)

# a is a 3 by 2 matrix
a = np.array([[1,2], [-9, 5], [3,3]])

# Choose first observation, first column
print (a[0, 0])
# Note: indices in Python start from 0; i.e. index of the first element is 0

# Choose third observation, second column
print (a[2, 1])

# Choose the second row. : means all columns
print (a[1, :])

# Choose the first column
print (a[:, 0])

# Choose the second and the third row, second colum
print (a[1:, 1])

1
3
[-9  5]
[ 1 -9  3]
[5 3]


*Assignment 1: Define a 4 by 4 numpy array, and select second and thrird row, first three columns*

There are several useful built-in functions in Numpy librarys. We will use several of them throughout the course.

# Pandas Arrays (Dataframes) are more advanced version of Numpy Arrays. Pandas DF is our main tool to work with data. One advantage of Pandas DFs compared with Numpy DFs is that columns in Pandas DFs can have names, like feature names in a dataset.

In [14]:
# import pandas library
import pandas as pd

In [15]:
# Define a Empty Pandas DF
df = pd.DataFrame(columns = ["first", "second", "thrid"])
df

Empty DataFrame
Columns: [first, second, thrid]
Index: []

In [17]:
# define a 3 by 3 Pandas DF
df = pd.DataFrame(columns = ["first", "second", "third"], data = [[1,2,3], [-8, 6, 2.3], [6,2,1]],)
df

first  second  third
0      1       2    3.0
1     -8       6    2.3
2      6       2    1.0

In [28]:
# choose the secons column
print (df.second)

# choose first and second column
print (df[["first", "second"]])

# choose thrid column, last two observations - we will use loc a lot
print (df.loc[1:, "third"])

# choose first and third row, second column
print (df.loc[[0, 2], "second"])

0    2
1    6
2    2
Name: second, dtype: int64
   first  second
0      1       2
1     -8       6
2      6       2
1    2.3
2    1.0
Name: third, dtype: float64
0    2
2    2
Name: second, dtype: int64


# Conditional selection of Pandas DF elements

In [31]:
# choose observations where third column higher than 2
print (df[df.third > 2])

# choose the first and third column of observations where third column higher than 2
print (df[df.third > 2][["first", "third"]])

# choose observations where thrid column is higher than 2 and second column higher than 5
print (df[(df.third > 2) & (df.second > 5)])

   first  second  third
0      1       2    3.0
1     -8       6    2.3
   first  third
0      1    3.0
1     -8    2.3
   first  second  third
1     -8       6    2.3


# Pandas are used to read data, like a data saved as .csv

In [35]:
# read data on Microsoft daily stock price, shared on eLearning

# this step is to read data on Google Drive
from google.colab import drive
drive.mount("/content/drive")

# read the data
microsoft_data=pd.read_csv("drive/My Drive/MSFT.csv")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


Pandas offer many features/functions to explore data

In [36]:
# take a look at the first rows
microsoft_data.head(2)

Date        Open        High         Low       Close   Adj Close  \
0  2018-08-27  109.269997  109.639999  108.510002  109.599998  103.838486   
1  2018-08-28  109.940002  110.500000  109.790001  110.260002  104.463814   

     Volume  
0  19662300  
1  19151500

In [37]:
# number of [observations, features]
microsoft_data.shape

(1258, 7)

Before we proceed, we need to get familiar with two other concepts: for loops , and if statement

In [39]:
# for loop: to go through a list one by one

# print numbers from 0 to 4
for i in range(5):
  print (i)

# Use For loop to print Open Price for 100th and 107th observations in Microsoft Data
for index in [99, 106]:
  print (microsoft_data.loc[index, "Open"])

0
1
2
3
4
107.459999
104.620003


In [43]:
# if statement: to run an operation, conditionally

# for the first 1000 observations in Microsoft data, print Dates where Close Price = High Price
for index in range (1000):
  if microsoft_data.loc[index, "Close"] == microsoft_data.loc[index, "High"]:
    print (microsoft_data.loc[index, "Date"])

2019-01-30
2022-08-12


*Assignment 2: Return on a stock is defined as Percentage Change in Price. In Microsoft Data, define a new column called "Return". Return at Date t is defined as (Close Price at Date t - Close Price at Date t-1) / Close Price at Date t-1*

Note that return can not be defined for the first observation.